theme: jekyll-theme-minimal
markdown: kramdown
title: kusto.blog
author: yonileibowitz
logo: resources/images/adx-logo.png
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache
google_site_verification: HtqjvGpOO7zMqHjzMmE6bM658bRZqGQewz_h-QyRnns
social:
  name: Yoni Leibowitz
  links:
    - https://www.linkedin.com/in/yonileibo/